echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo "<title>My Bash Page</title>"
echo "</head>"
echo "<body>"
echo "<h1>Hello, Bash!</h1>"
echo "<p>This is a simple Bash script that generates HTML content.</p>"
echo "</body>"
echo "</html>"